#---------------------------------------#
#       environment configuration       #
#---------------------------------------#

#These are required by the AWS SDK even though they aren't used with dynamo db local.
environment:
  AWS_ACCESS_KEY_ID: AKID
  AWS_SECRET_ACCESS_KEY: SECRET
  AWS_REGION: us-east-1
  packageVersion: 0.1.0

init:
- ps: $env:buildVersion = "$env:packageVersion.$env:appveyor_build_number"
- ps: $env:nugetVersion = "$env:packageVersion-beta-$env:appveyor_build_number"

assembly_info:
  patch: true
  file: '**\VersionInfo.*'
  assembly_version: '$(buildVersion)'
  assembly_file_version: '$(buildVersion)'
  assembly_informational_version: '$(nugetVersion)'

pull_requests:
  do_not_increment_build_number: true
branches:
  only:
  - master
nuget:
  disable_publish_on_pr: true

#---------------------------------#
#       build configuration       #
#---------------------------------#
before_build:
  - nuget restore src\QuartzNET-DynamoDB.sln 
platform:
  - Any CPU
configuration: Release
build:
  parallel: true                  
  project: src\QuartzNET-DynamoDB.sln   

after_build:
- ps: nuget pack $env:APPVEYOR_BUILD_FOLDER\src\QuartzNET-DynamoDB\QuartzNET-DynamoDB.csproj -IncludeReferencedProjects -version "$env:nugetVersion" -BasePath $env:APPVEYOR_BUILD_FOLDER\src\QuartzNET-DynamoDB

#---------------------------------#
#       test configuration        #
#---------------------------------#
before_test:
  - ps: mkdir c:/tmp
  - ps: write-host "Downloading latest version of DynamoDB local"
  - ps: (new-object net.webclient).DownloadFile('http://dynamodb-local.s3-website-us-west-2.amazonaws.com/dynamodb_local_latest.zip', 'c:/tmp/dynamodb_local.zip')
  - ps: write-host "Extracting latest version of DynamoDB local"
  - ps: Expand-Archive c:/tmp/dynamodb_local.zip -DestinationPath c:/tmp
  - ps: write-host "Running DynamoDB local in a new PS process in the background..."
  - ps: $MyProcess = Start-Process javaw.exe -PassThru -ArgumentList '-Djava.library.path=c:/tmp/DynamoDBLocal_lib', '-jar', 'c:/tmp/DynamoDBLocal.jar', '-inMemory' 

test:
  assemblies: 
    - QuartzNET-DynamoDB.Tests.dll

artifacts:
  - path: '**\QuartzNET*.nupkg'

deploy:
  provider: NuGet
  api_key:
    secure: 2qbyIGUhwVPC5BpyWgLtgLNvc6DsblwAIuxTTEI0qXX3BF28+I35qoBILwB8Fe79
  skip_symbols: false
  on:
    branch: master